### ISSUE TITLE
Why does the return type has a optional decode Error?

### ISSUE THREAD

**Issue by pulasthibandara** [YBogomolov/fetcher-ts#9]
I've been scratching my head not able to figure out the reason for the `run()`'s return type's signature. Is it possible to have a decode error while also having an output?

I was expecting a return type of `run()` to be `Either<io.Error, To>`, where `To` itself can be an Either.

What was the reason to have a tuple with an optional decode error?

**Comment by YBogomolov** [comment]
Thank you for your question! The io-ts type is not a decoder, actually, but rather a validator — the response data could be present, but do not pass validation. This can happen for a lot of reasons — say, you expect server's response to contain a strict field of type `A`, but the back-end returns `A | null`.
Initially I was thinking of using `These` instead of tuple, but decided to go for a more approachable API design.

**Comment by pulasthibandara** [comment]
Nice!, so it gives the consumer to decide to fail or tolerate errors. On a side note, I was looking for an `Ior` type in `fp-ts` but couldn't find it. Now I see what I wanted was `These`.

**Comment by pulasthibandara** [comment]
Thanks for the prompt response and this library :)

**Comment by YBogomolov** [comment]
Thank you! I'm closing this issue, but if you have any additional questions, please feel free to reopen it.
